# Generated by Django 5.2 on 2025-04-27 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juez', '0002_testcase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCase',
            new_name='TestCases',
        ),
        migrations.RenameModel(
            old_name='Problem',
            new_name='Problemas',
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField()),
                ('language_id', models.IntegerField()),
                ('stdin', models.TextField(blank=True, default='')),
                ('output', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CORRECT', 'Correct'), ('WRONG', 'Wrong Answer')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='juez.problemas')),
            ],
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
