# Generated by Django 5.2 on 2025-04-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juez', '0003_rename_testcase_testcases_rename_problem_problemas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemas',
            old_name='created_at',
            new_name='creacion',
        ),
        migrations.RenameField(
            model_name='problemas',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='problemas',
            old_name='sample_input',
            new_name='ejemplo_input',
        ),
        migrations.RenameField(
            model_name='problemas',
            old_name='sample_output',
            new_name='ejemplo_output',
        ),
        migrations.RenameField(
            model_name='problemas',
            old_name='input_description',
            new_name='input_descripcion',
        ),
        migrations.RenameField(
            model_name='problemas',
            old_name='output_description',
            new_name='output_descripcion',
        ),
        migrations.RenameField(
            model_name='problemas',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='submissions',
            old_name='created_at',
            new_name='creacion',
        ),
        migrations.RenameField(
            model_name='submissions',
            old_name='problem',
            new_name='problema',
        ),
        migrations.RenameField(
            model_name='testcases',
            old_name='created_at',
            new_name='creacion',
        ),
        migrations.RenameField(
            model_name='testcases',
            old_name='problem',
            new_name='problema',
        ),
        migrations.AlterField(
            model_name='submissions',
            name='status',
            field=models.CharField(choices=[('CORRECT', 'Correct'), ('WRONG', 'Wrong Answer')], default='WRONG', max_length=20),
        ),
    ]
