# Generated by Django 5.1.4 on 2025-06-02 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juez', '0005_remove_problemas_expected_output_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('input_description', models.TextField()),
                ('output_description', models.TextField()),
                ('example_input', models.TextField()),
                ('example_output', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.CharField(choices=[('Fácil', 'Fácil'), ('Media', 'Media'), ('Difícil', 'Difícil')], default='Media', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='submissions',
            name='problema',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='problema',
        ),
        migrations.RenameField(
            model_name='submissiontestcaseresult',
            old_name='error',
            new_name='error_message',
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('source_code', models.TextField()),
                ('language_id', models.IntegerField()),
                ('stdin', models.TextField(blank=True, default='')),
                ('output', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CORRECT', 'Correct'), ('WRONG', 'Wrong Answer'), ('ERROR', 'Runtime/Error'), ('TIMEOUT', 'Time Limit Exceeded')], default='PENDING', max_length=20)),
                ('execution_time', models.CharField(blank=True, max_length=20, null=True)),
                ('memory_usage', models.CharField(blank=True, max_length=20, null=True)),
                ('error_output', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='juez.problem')),
            ],
        ),
        migrations.AlterField(
            model_name='submissiontestcaseresult',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_result', to='juez.submission'),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case', to='juez.problem')),
            ],
        ),
        migrations.DeleteModel(
            name='Problemas',
        ),
        migrations.DeleteModel(
            name='TestCases',
        ),
        migrations.DeleteModel(
            name='Submissions',
        ),
    ]
