# Generated by Django 5.2 on 2025-05-16 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juez', '0004_rename_created_at_problemas_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemas',
            name='expected_output',
        ),
        migrations.AddField(
            model_name='problemas',
            name='dificultad',
            field=models.CharField(choices=[('Facil', 'Fácil'), ('Media', 'Media'), ('Dificil', 'Difícil')], default='Media', max_length=10),
        ),
        migrations.AddField(
            model_name='submissions',
            name='error_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='execution_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='memory',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CORRECT', 'Correct'), ('WRONG', 'Wrong Answer'), ('ERROR', 'Runtime/Error'), ('TIMEOUT', 'Time Limit Exceeded')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='SubmissionTestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('user_output', models.TextField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_results', to='juez.submissions')),
            ],
        ),
    ]
